version: 2.1
orbs:
  docker: circleci/docker@2.1.4
  snyk: snyk/snyk@1.5.0
jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0.7
    steps:
      - checkout
      - run: mvn clean package
  test:
    docker:
      - image: cimg/openjdk:17.0.7
    steps:
      - checkout
      - run: |
          echo "Running tests..."
          mvn test
  scan:
    docker:
        - image: cimg/openjdk:17.0.7
    environment:
        IMAGE_NAME: mangofarmer/education-space
    steps:
        - checkout
        - setup_remote_docker      
        - docker/check
        - run: docker build -t $IMAGE_NAME .
        - snyk/scan:
            severity-threshold: critical
            docker-image-name: $IMAGE_NAME
            
  build-and-push:
    executor: docker/docker
    docker:
      - image: cimg/openjdk:17.0.7
        auth:
            username: $DOCKER_LOGIN
            password: $DOCKER_PASSWORD
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          image: mangofarmer/education-space
          tag: ${CIRCLE_SHA1}
      - docker/push:
          image: mangofarmer/education-space
          tag: ${CIRCLE_SHA1}
            
workflows:
  ci_flow:
    jobs:
      - build:
          filters:
            branches:
              only: develop
      - test:
          requires:
            - build
           filters:
            branches:
              only: develop     
      - scan:
          requires:
            - build
      - build-and-push:
          requires:
            - test
            - scan
